### Assignment 1: Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
arr1= np.random.randint(1,21, size= (5,5))
arr1[:,2] = 1

print(arr1)

[[10 19  1  1  1]
 [ 3  7  1 16  8]
 [ 8 16  1 17 12]
 [ 4 14  1 18  5]
 [13  6  1  8 20]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [11]:
arr2 = np.arange(1,17).reshape((4,4))
np.fill_diagonal(arr2, 0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [6]:
arr3 = np.arange(1,37).reshape((6,6))
print(arr3[3:, 2:5])

[[21 22 23]
 [27 28 29]
 [33 34 35]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [9]:
arr4 = np.random.randint(1,25, size = (5,5))
print(arr4)

[[18 11 19  1 12]
 [ 1  8  5  4  1]
 [10 23 20 15 13]
 [ 9  9 18 10 22]
 [24  8 17 23  5]]


### Assignment 3: Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [16]:
arr5 = np.random.randint(1,11, size=(3,4))
arr6 = np.random.randint(1,11, size=(3,4))
print(arr5)
# print(arr5+arr6)

[[3 4 6 3]
 [1 4 5 7]
 [2 6 5 3]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [19]:
row_sum = np.sum(arr5, axis=1)
column_sum = np.sum(arr5, axis=0)
print(row_sum)
print(column_sum)

[16 17 16]
[ 6 14 16 13]
