### Assignment 1: Array Creation and Manipulation
1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
arr1= np.random.randint(1,21, size= (5,5))
arr1[:,2] = 1

print(arr1)

[[ 1 15  1  6 19]
 [19 14  1  5 14]
 [10  2  1  4 14]
 [12 10  1 12 20]
 [16  6  1  5  9]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [11]:
arr2 = np.arange(1,17).reshape((4,4))
np.fill_diagonal(arr2, 0)
print(arr2)

[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing
1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [6]:
arr3 = np.arange(1,37).reshape((6,6))
print(arr3[3:, 2:5])

[[21 22 23]
 [27 28 29]
 [33 34 35]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [9]:
arr4 = np.random.randint(1,25, size = (5,5))
print(arr4)

[[18 11 19  1 12]
 [ 1  8  5  4  1]
 [10 23 20 15 13]
 [ 9  9 18 10 22]
 [24  8 17 23  5]]


### Assignment 3: Array Operations
1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [16]:
arr5 = np.random.randint(1,11, size=(3,4))
arr6 = np.random.randint(1,11, size=(3,4))
print(arr5)
# print(arr5+arr6)

[[3 4 6 3]
 [1 4 5 7]
 [2 6 5 3]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [19]:
row_sum = np.sum(arr5, axis=1)
column_sum = np.sum(arr5, axis=0)
print(row_sum)
print(column_sum)

[16 17 16]
[ 6 14 16 13]


### Assignment 4: Statistical Operations
1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [9]:
arr7 = np.random.randint(1,26, size=(5,5))
mean = np.mean(arr7)
median1 = np.median(arr7)
standard_deviation = np.std(arr7)
variance=  np.var(arr7)
print(mean, median1, standard_deviation, variance)

9.96 8.0 6.427939016512213 41.318400000000004


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [14]:
arr8 = np.arange(1,10).reshape((3,3))
mean1 = np.mean(arr8)
std1 = np.std(arr8)
normalized_array = (arr8-mean)/std1
print(normalized_array)

[[-3.47019308 -3.08289474 -2.69559641]
 [-2.30829807 -1.92099974 -1.53370141]
 [-1.14640307 -0.75910474 -0.3718064 ]]


### Assignment 5: Broadcasting
1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [16]:
arr9 = np.random.randint(1,10, size=(3,3))
oned_array = np.random.randint(1,10, size=(3,))
print(arr9)
print(oned_array)
print(arr9+oned_array)

[[2 7 9]
 [5 8 8]
 [1 8 5]]
[4 1 4]
[[ 6  8 13]
 [ 9  9 12]
 [ 5  9  9]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra
1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [18]:
matrix = np.random.randint(1, 11, size=(3, 3))

determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

inverse = np.linalg.inv(matrix)
print("Inverse:", inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues:", eigenvalues)

Determinant: -5.000000000000007
Inverse: [[ 0.2  0.2 -0.6]
 [-0.4 -5.4 10.2]
 [ 0.2  4.2 -7.6]]
Eigenvalues: [17.2794276   3.79678463 -0.07621223]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [19]:
array1 = np.random.randint(1, 11, size=(2, 3))
array2 = np.random.randint(1, 11, size=(3, 2))

# Perform matrix multiplication
result = np.dot(array1, array2)
print("Matrix multiplication result:")
print(result)

Matrix multiplication result:
[[199  67]
 [125  60]]


### Assignment 7: Advanced Array Manipulation
1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [22]:
arr10 = np.arange(1,10).reshape(3,3)
print(arr10.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


### Assignment 8: Fancy Indexing and Boolean Indexing
1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [24]:
arr11 = np.random.randint(1,11, size=(5,5))
print(arr11)
print(arr11[[0,0,-1,-1],[0,-1,0,-1]])

[[ 8  8  1  6  2]
 [ 8  2 10 10  2]
 [ 4  8 10  6  5]
 [ 3 10  6  8  2]
 [ 1  8  6 10 10]]
[ 8  2  1 10]


### Assignment 9: Structured Arrays
1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [27]:
data_type = [('Name', 'U10'),('Age', 'i4'), ('weight', 'f4')]
structured_array = np.array([('Jawad', 25, 66.6), ('Juhana', 24, 51.5), ('Areez', 7, 21.5)], dtype=data_type)
print(structured_array)
sorted_array = np.sort(structured_array, order='Age')
print(sorted_array)

[('Jawad', 25, 66.6) ('Juhana', 24, 51.5) ('Areez',  7, 21.5)]
[('Areez',  7, 21.5) ('Juhana', 24, 51.5) ('Jawad', 25, 66.6)]


### Assignment 10: Masked Arrays
1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements

In [29]:
import numpy.ma as ma

array3 = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array3, 10)
print(array3)
print(masked_array)
print(masked_array.sum())

[[11 12  9 13]
 [ 6 13  3  2]
 [11  8  2  9]
 [ 6  7  8 17]]
[[-- -- 9 --]
 [6 -- 3 2]
 [-- 8 2 9]
 [6 7 8 --]]
60
