In [4]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6,]])

print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [ ]:
arr1 = np.array([[1,2,3], [4,5,6], [6,11,2]])
arr2 = np.array([1,2,3,])
arr3 = arr1+arr2

# print(np.sqrt(arr1+arr2))
print(arr1)
# print(arr1[1:]) 
# print(arr1[0:,1:])
print(arr[0:2, 2:])

[[ 1  2  3]
 [ 4  5  6]
 [ 6 11  2]]
[[3]
 [6]]


In [5]:
import pandas as pd

In [12]:
df = pd.read_csv('data.csv')
df

Name  Age   City University
0   Jawad   25  Dhaka        IUT
1  Juhana   24  Dhaka       Brac
2   Afeef   25  Dhaka        IUT
3   Jawad   25  Dhaka        IUT
4  Juhana   24  Dhaka       Brac
5   Afeef   25  Dhaka        IUT

In [17]:
df = df.rename(columns={'Name': 'Full Name'})
df.head()

Full Name  Age   City University
0     Jawad   25  Dhaka        IUT
1    Juhana   24  Dhaka       Brac
2     Afeef   25  Dhaka        IUT
3     Jawad   25  Dhaka        IUT
4    Juhana   24  Dhaka       Brac